config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :comments, only: %i[create destroy]
    get :purge, on: :member
    get :only_self, on: :collection
  end

  root to: 'posts#index'

  devise_for :admin_users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :body, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image
  has_many :comments, dependent: :destroy
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :name, length: {maximum: 20}
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  before_validation :capitalizing_name

  def capitalizing_name
    name.capitalize! if name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_commentable_post

  def create
    @comment = @post.comments.build(comment_params)
    if @comment.save
      redirect_to @post, notice: "Комментарий сохранён!"
    else
      render "posts/show"
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    if current_user&.id == @comment.user.id
      @comment.destroy
      redirect_to @post, notice: "Комментарий удалён!"
    else
      redirect_to @post, alert: "Нельзя удалять чужие комментарии!"
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user_id: current_user.id)
  end

  def set_commentable_post
    @post = Post.find(params[:post_id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_post, only: %i[show edit update destroy purge]
  before_action :compare_id, only: %i[edit update destroy]

  def index
    @pagy, @posts = pagy(Post.order(created_at: :desc), items: 15)
  end

  def show
  end

  def new
     @post = Post.new
  end

  def edit
  end

  def purge
    @post.image.purge
    render :edit
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "Пост создан!"
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Изменения сохранены!"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: "Пост удалён!"
  end

  def only_self
    @pagy, @posts = pagy(Post.where(user_id: current_user.id).order(created_at: :desc), items: 15)
    render :index
  end

  private

  def compare_id
    return if current_user&.id == @post.user.id
    redirect_to posts_path, alert: "Нельзя редактировать чужие посты!"
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.erb
<% comments = Comment.where(post_id: post.id).order(created_at: :desc) %>

<% comments.each do |comment| %>
  <div class="card mx-auto mb-1" style="width: 35%">
    <div class="card-header d-flex flex-md-row align-items-center justify-content-between py-1">
      <div class="fs-5"><%= comment.user.name %>
        <small class="text-muted fs-6 ms-2"><%= comment.user.email %></small>
      </div>
      <small class="text-muted">
        <div><%= comment.created_at.strftime("%d.%m.%Y в %H:%M") %></div>
      </small>
    </div>
    <div class="card-body">
      <p><%= comment.body %></p>
    </div>
    <% if current_user&.id == comment.user.id %>
      <div class="text-end card-footer py-1"><%= button_to "Удалить", post_comment_path(post, comment),
        data: {turbo_confirm: "Удалить комментарий?"}, method: :delete, class: "btn btn-dark btn-sm" %></div>
    <% end %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<div class="form-control mx-auto my-4 pt-2" style="width: 35%">
  <%= form_with data: {turbo: false}, model: [post, comment || post.comments.build] do |form| %>
    <%= render "shared/errors", object: comment %>

    <%= form.label :body, "Напишите ваш комментарий", class: "form-label mt-1" %>
    <%= form.text_area :body, rows: 3, class: "form-control" %>

    <p class="text-end mb-1"><%= form.submit "Сохранить",
      class: "btn btn-dark btn-sm mt-2"%>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="py-2 bg-light border-bottom">
  <div class="container d-flex flex-wrap">
    <ul class="nav me-auto">
      <li class="nav-item"><%= link_to "Главная", root_path, class: "nav-link link-dark px-2" %></li>
    </ul>
    <ul class="nav">
      <% if user_signed_in? %>
        <li class="nav-item"><%= link_to current_user.name.present? ? "#{current_user.name}" : "Профиль",
          edit_user_registration_path, class: "nav-link link-dark px-2 fst-italic" %></li>
        <li class="nav-item"><%= button_to "Выйти", destroy_user_session_path, method: :delete,
          class: "px-2 my-1 btn btn-sm btn-dark" %></li>
      <% else %>
        <li class="nav-item"><%= link_to "Регистрация", new_user_registration_path,
          class: "nav-link link-dark px-2" %></li>
        <li class="nav-item"><%= link_to "Войти", new_user_session_path,
          class: "nav-link link-dark px-2" %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "/layouts/header" %>
    <% if flash[:notice].present? %>
      <p class="text-center alert alert-success mx-2 mt-1"><%= flash[:notice] %></p>
    <% elsif flash[:alert].present? %>
      <p class="text-center alert alert-danger mx-2 mt-1"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="form-control mx-auto" style="width: 65%">
  <%= form_with data: {turbo: false}, model: post do |form| %>

    <%= form.label :title, "Название", class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>

    <%= form.label :content, "Содержание", class: "form-label mt-3" %>
    <%= form.text_area :content, rows: 10, class: "form-control" %>

    <% if post.image.present? && post.persisted? %>
      <p class="text-center">Текущая картинка (нажмите на неё, чтобы удалить)</p>
      <p class="text-center">
        <%= link_to image_tag(post.image.variant(resize_to_fit: [300, 300])), purge_post_path(post) %>
      </p>
    <% else %>
      <div class="my-3">
        <%= form.label :image, "Выберите картинку(опционально)", class: "form-label" %>
        <%= form.file_field :image, class: "form-control" %>
      </div>
    <% end %>

    <p class="text-center"><%= form.submit "Сохранить", class: "btn btn-dark btn-lg my-1"%></p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<h2 class="text-center">Редактируем пост <%= @post.title %></h2>

<div class="mx-auto" style="width: 65%">
  <%= render "shared/errors", object: @post %>
</div>


<%= render "form", post: @post %>

app/views/posts/index.html.erb
<% if params[:action]=="index" %>
  <h2 class="text-center mt-3">Все посты</h2>
<% else %>
  <h2 class="text-center mt-3">Мои посты</h2>
<% end %>

<!-- не показываем ссылки, если не залогинен -->
<% if current_user %>
  <p class="text-center">
    Показать
    <% if params[:action]=="index" %>
      <%= link_to "только мои посты", only_self_posts_path %>
    <% else %>
      <%= link_to "все посты", posts_path %>
    <% end %>
  </p>
<% end %>

<% if @posts.present? %>
  <p class="text-center"><%= link_to "Создать пост", new_post_path if current_user %></p>
  <nav class="pagination justify-content-center"><%== pagy_bootstrap_nav @pagy %></nav>

  <% @posts.each do |post| %>
    <div class="card mx-auto mb-1" style="width: 50%">
      <div class="card-header d-flex flex-md-row align-items-center justify-content-between py-1">
        <div class="fs-5"><%= link_to "#{post.title}", post_path(post), class: "text-dark text-underline-hover" %></div>
        <small class="text-muted">
          <div><%= post.created_at.strftime("%d.%m.%Y в %H:%M") %></div>
        </small>
      </div>
      <div class="card-body">
        <p><%= truncate (post.content), length: 150 %></p>
      </div>
    </div>
  <% end %>

  <nav class="pagination justify-content-center mt-3"><%== pagy_bootstrap_nav @pagy %></nav>
<% else %>
  <p class="text-center">Постов пока нет</p>
  <p class="text-center"><%= link_to "Вы можете создать первый", new_post_path if current_user %></p>
<% end %>

app/views/posts/new.html.erb
<h2 class="text-center mt-3">Добавляем новый пост</h2>

<div class="mx-auto" style="width: 65%">
  <%= render "shared/errors", object: @post %>
</div>

<%= render "form", post: @post %>

app/views/posts/show.html.erb
<h2 class="text-center mt-3"><%= @post.title %></h2>

<% if @post.image.attached? %>
  <p class="text-center"><%= link_to image_tag(@post.image.variant(resize_to_fit: [500, 500])), @post.image %></p>
<% end %>
<div class="container">
  <%= @post.content %>
</div>

<!-- не показываем кнопки, если пост не принадлежит юзеру -->
<% if current_user&.id == @post.user.id %>
  <div class="container text-center">
    <div class="d-inline-block">
      <%= button_to "Редактировать пост", edit_post_path(@post), method: :get, class: "btn btn-dark" %>
    </div>
    <div class="d-inline-block">
      <%= button_to "Удалить пост", post_path(@post),
        data: {turbo_confirm: "Удалить пост #{@post.title}"}, method: :delete, class: "btn btn-dark" %>
    </div>
  </div>
<% end %>

<%= render "comments/form", post: @post, comment: @comment if current_user %>

<%= render "comments/comments", post: @post %>

<p class="text-center mt-2"><%= link_to "Назад ко всем постам", posts_path %></p>

app/views/shared/_errors.html.erb
<% if object&.errors&.any? %>
  <ul class="alert alert-danger">
    <% object.errors.full_messages.each do |msg| %>
      <li class="mx-2"><%= msg %></li>
    <% end %>
  </ul>
<% end %>